apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvc.yaml
  - ts-ingress.yaml
  - qbittorrent.yaml
  - plex.yaml
  - jellyfin.yaml
  - overseerr.yaml
  - apprise-api.yaml
  - tautulli.yaml
  - msmtpd.yaml
  - radarr.yaml
  - sonarr.yaml
  - lidarr.yaml
  - bazarr.yaml
  - prowlarr.yaml
  - configarr.yaml
  - unmonitorr.yaml
  - pihole.yaml
