apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ollama.yaml
  - openwebui.yaml
  - openwebui-credentials-env-sealed-secret.yaml
  - local-ai.yaml
  - langflow.yaml

configurations:
  - kustomizeconfig.yaml
